# Copyright (c) 2026 Agentic Company. All rights reserved.
# Proprietary and non-commercial use only.

"""CoComputer agent tools — computer control primitives for ADK."""

from nexus.tools.computer import (
    move_mouse,
    left_click,
    right_click,
    double_click,
    triple_click,
    type_text,
    press_key,
    scroll_screen,
    drag,
)
from nexus.tools.bash import run_command
from nexus.tools.screen import take_screenshot
from nexus.tools.browser import open_browser
from nexus.tools.bg_task import request_background_task
from nexus.tools.monitor import schedule_monitoring_task
from nexus.tools.skills import read_skill, read_skill_file
from nexus.tools.workspace import (
    prepare_task_workspace,
    initialize_task_state,
    update_task_state,
    read_task_state,
    write_todo_list,
    update_todo_item,
    write_workspace_file,
    read_workspace_file,
    list_workspace_files,
)
from nexus.tools.docs import (
    extract_pdf_text,
    generate_pdf_report,
    generate_excel_report,
    generate_docx_report,
    generate_pptx_report,
    publish_html_artifact,
    publish_app_preview,
    save_as_artifact,
)
from nexus.tools.web import web_search, scrape_web_page
from nexus.tools.integrations import (
    search_drive,
    read_drive_file,
    create_drive_doc,
    upload_drive_file,
    github_search_repos,
    github_read_file,
    github_list_issues,
    github_create_issue,
    github_summarize_pr,
    github_clone_repo,
    github_create_repo,
    github_push,
    tavily_search,
    tinyfish_web_agent,
    vyora_list_agents,
    vyora_list_numbers,
    vyora_start_call,
    vyora_list_calls,
    vyora_get_call,
    openai_web_search,
    render_ui,
    gmail_search,
    gmail_read,
    gmail_send,
    tasks_list,
    tasks_create,
    calendar_list,
    calendar_get,
    calendar_create,
    calendar_update,
    calendar_delete,
)
from nexus.tools.ui_control import show_desktop_panel, show_workflow_panel
from nexus.tools.templates import (
    propose_workflow_template,
    update_workflow_template,
    publish_workflow_template,
)

ALL_TOOLS = [
    prepare_task_workspace,
    initialize_task_state,
    update_task_state,
    read_task_state,
    write_todo_list,
    update_todo_item,
    write_workspace_file,
    read_workspace_file,
    list_workspace_files,
    read_skill,
    read_skill_file,
    web_search,
    scrape_web_page,
    extract_pdf_text,
    generate_pdf_report,
    generate_excel_report,
    generate_docx_report,
    generate_pptx_report,
    publish_html_artifact,
    publish_app_preview,
    save_as_artifact,
    search_drive,
    read_drive_file,
    create_drive_doc,
    upload_drive_file,
    github_search_repos,
    github_read_file,
    github_list_issues,
    github_create_issue,
    github_summarize_pr,
    github_clone_repo,
    github_create_repo,
    github_push,
    tavily_search,
    tinyfish_web_agent,
    vyora_list_agents,
    vyora_list_numbers,
    vyora_start_call,
    vyora_list_calls,
    vyora_get_call,
    openai_web_search,
    render_ui,
    gmail_search,
    gmail_read,
    gmail_send,
    tasks_list,
    tasks_create,
    calendar_list,
    calendar_get,
    calendar_create,
    calendar_update,
    calendar_delete,
    take_screenshot,
    run_command,
    move_mouse,
    left_click,
    right_click,
    double_click,
    triple_click,
    type_text,
    press_key,
    scroll_screen,
    drag,
    open_browser,
    request_background_task,
    schedule_monitoring_task,
    show_desktop_panel,
    show_workflow_panel,
    propose_workflow_template,
    update_workflow_template,
    publish_workflow_template,
]
